[phases.setup]
aptPkgs = ['default-libmysqlclient-dev', 'pkg-config', 'libjpeg-dev', 'zlib1g-dev']

[phases.install]
cmds = ['pip install -r requirements.txt']

[start]
cmd = 'python manage.py migrate && python manage.py collectstatic --noinput && gunicorn ghosthire.wsgi:application'
